print("Enter Employee Details like:")
emp_name=input("Enter Employee Name:")
emp_phno=input("Enter Employee Phone Number:")
emp_address=input("Enter Address of Employee:")
emp_salary=input("Enter Employee Salary:")
emp_designation=input("Enter Employee Designation")
emp_date_of_birth=input("Enter Employee DOB:")
emp_blood_group=input("Enter Employee Blood Group:")
print("Entered Employee Details are:")
print("..............................")
print("Employee Name:\t",emp_name)
print("Employee Phone Number:\t",emp_phno)
print("Employee Address:\t",emp_address)
print("Employee Salary:\t",emp_salary)
print("Employee Designation:\t",emp_designation)
print("Employee DOB:\t",emp_date_of_birth)
print("Employee Blood Group:\t",emp_blood_group)
